# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CA4015 Music Recommendation Task
author: Anthony Reidy, 18369643
logo: images/music-rec-logo.png
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 500

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: Anthony_Reidy.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - _bibliography/references.bib

# In _config.yml
sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/reidya3/MusicArtistRecommendationSystem  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
